### PR TITLE
Fix compile error in Remote Control Competition

### LINKED ISSUE #2330: "Remote Control Competition" exercice: Incoherent task and test
In this exercise, the task 4 asks for implementing a static method sorting two different `ProductionRemoteControlCar` in arguments, but the test code pass in arguments a `List<ProductionRemoteControlCar>` object...

One could think of either modifying the source code or the task.

### PR DESCRIPTION
**Pull request by sanderploegsma**
The default implementation of the `TestTrack` class in Remote Control Competition doesn't match the expected signature in the unit tests, causing the compilation to fail until the student updates the dummy method to match the correct signature.

It looks like this was introduced in #2283 where the unit tests were updated but the stub implementation wasn't.

Note that this is a duplicate of #2331, #2336 and #2337, but the former updates the assertions in a way that doesn't make a lot of sense, and the latter two update the stub but not the exemplar implementation nor the instructions.

Fixes #2330, #2318

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sanderploegsma** [comment]
And a side note: I don't get why this wasn't caught in CI? AFAIK the CI test job runs the unit tests on the examplar implementations, right? This should also have resulted in a compilation error, so I suspect the CI job is not 100% doing what it's supposed to do...

**Comment by sanderploegsma** [comment]
Looks like @IsaacG beat me to it, so closing as duplicate of #2337
